# ==============================================================================
# Dynamic Variable Declarations - Generated by Scaffolder
# ==============================================================================

variable "project_id" {
  description = "The target ephemeral GCP project allocated for the participant"
  type        = string
}

variable "region" {
  description = "The target deployment region"
  type        = string
  default     = "europe-west3"
}

variable "iap_member" {
  description = "The IAM member string for the participant (e.g., user:devstar@gcplab.me)"
  type        = string
}

variable "alloydb_vectors_alloydb_instance_cpu_count" {
  description = "Number of vCPUs for the AlloyDB primary instance (minimum 2)"
  type        = number
  default     = 2
}

variable "alloydb_vectors_alloydb_password" {
  description = "Password for the initial AlloyDB database user"
  type        = string
  default     = "alloydb-hackathon-password"
}
